source 'http://rubygems.org'

gem 'capybara'
gem 'chromedriver-helper'
gem 'pry'
gem 'pry-byebug'
gem 'pry-rails'
gem 'rake'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'webdriver-highlighter'
gem 'rest-client'
gem 'geckodriver-helper'
gem 'gmail'